// Generated by CoffeeScript 1.10.0

/**
 * indexRegex
 *
 * @return  {Regexp}
 */

(function() {
  'use strict';
  var indexRegex;

  module.exports = indexRegex = function() {
    return /\/$/;
  };

}).call(this);
