// Generated by CoffeeScript 1.10.0

/**
 * isFunction
 *
 * @return  {Boolean}
 */

(function() {
  'use strict';
  var isFunction, toString;

  toString = Object.prototype.toString;

  module.exports = isFunction = function(value) {
    return toString.call(value) === '[object Function]';
  };

}).call(this);
