// Generated by CoffeeScript 1.10.0

/**
 * objectForEach
 *
 * @param  {Object} object
 * @param  {Function} callback
 * @param  {Any} context = global
 */

(function() {
  'use strict';
  var arrayForeach, keys, objectForEach;

  keys = require('object-keys');

  arrayForeach = require('array-foreach');

  module.exports = objectForEach = function(object, callback, context) {
    if (context == null) {
      context = global;
    }
    return arrayForeach(keys(object), function(key, i) {
      return callback.call(context, object[key], key, i, object);
    });
  };

}).call(this);
